### ISSUE TITLE
无法访问tiktok

### ISSUE THREAD

**Issue by tporwx** [QiuSimons/openwrt-mos#107]
无法打开tiktok.com
显示：
无法访问此网站
连接已重置。
请试试以下办法：

检查网络连接
[检查代理服务器和防火墙](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_RESET

**Comment by sbwml** [comment]
mosdns 是dns 解析工具，不是帮你去实现一些无法访问的网站

**Comment by tporwx** [comment]
当然是配合ssrp用的，不然我为什么不说不能访问google、youtube呢

**Comment by tporwx** [comment]
> mosdns 是dns 解析工具，不是帮你去实现一些无法访问的网站

会有人单独用mosdns? 有什么意义？

**Comment by sbwml** [comment]
> 当然是配合ssrp用的，不然我为什么不说不能访问google、youtube呢

很显然你要去解决他的思路就已经错了，这依然跟dns毫无关系，做好正确的 URL Rewrite，使用对的代理节点，即使你使用运营商dns 解析tiktok 域名，他一样可以正常观看

**Comment by tporwx** [comment]
> > 当然是配合ssrp用的，不然我为什么不说不能访问google、youtube呢
> 
> 很显然你要去解决他的思路就已经错了，这依然跟dns毫无关系，做好正确的 URL Rewrite，使用对的代理节点，即使你使用运营商dns 解析tiktok 域名，他一样可以正常观看

首先，不开代理是访问不了tiktok.com的，至少我本地如此；
其次，单独用ssrp或者passwall走代理是可以正常访问的，但是配合mosdns就不行。
很显然这是mosdns的解析问题。

**Comment by sbwml** [comment]
这也太顶了

**Comment by QiuSimons** [comment]
有没有一种可能性，黑名单强制海外解析的功能，是给有特定需求的人使用的

**Comment by tporwx** [comment]
非常有可能，看来就是给我准备的，黑名单啪啪那么一加，你猜怎么着？
还是访问不了！

**Comment by qingtian110** [comment]
> 有没有一种可能性，黑名单强制海外解析的功能，是给有特定需求的人使用的

😄试了一下，mosdns规则里面的黑名单是拦截域名去广告用的，不是强制海外解析功能的，白名单倒是强制国内解析并且可以突破广告拦截规则误杀的域名

不过大佬说的这个 “强制海外解析” 功能我觉得很值得被加进来，这样一来域名解析就彻底允许被DIY了

**Comment by qingtian110** [comment]
> 我用美国、日本、南非的节点均无法访问。 至于“黑名单强制海外解析的功能”，如果指的是ssrp的强制走代理，那也是没用的， 如果这功能是mosdns的，luci没有适配此功能吧？不知道这可能性是啥？

另外我觉得也不是你dns上出现的问题，你上面说如果直接使用ssrp自带的dns插件就可以正常使用，有没有一种可能这个代理插件本身是有什么代理规则是需要配合它本身的dns实现的？tiktok刚好在这规则里面。一切别的dns ，tiktok就没有被代理上了（纯瞎猜，我路由器没有装ssrp试不了）。如果是这样    你可以试试把SSRP 设置成全局代理模式+mosdns 看看能不能访问

**Comment by jeram555** [comment]
我电脑端可以访问 tiktok啊？有什么问题？
但手机端必须开圈x或火箭
