### ISSUE TITLE
26日编译的固件无法启动mosdns

### ISSUE THREAD

**Issue by blueveryday** [QiuSimons/openwrt-mos#108]
> Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.633Z	info	v3/main.go:157	current working directory: /etc/mosdns/
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.634Z	info	v3/main.go:223	mosdns ver: cee9e6d
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.634Z	info	v3/main.go:224	arch: mipsle, os: linux, go: go1.18.1
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.634Z	info	coremain/run.go:65	loading config	{"file": "./def_config.yaml"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.634Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.loglv"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.642Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.loglv", "stdout": "error"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.642Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.logfile"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.649Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.logfile", "stdout": "/dev/null"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.649Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.656Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port", "stdout": "5335"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.656Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.663Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port", "stdout": "5335"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.664Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 0"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.755Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 0", "stdout": "218.201.17.2"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.755Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 1"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.852Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 1", "stdout": "218.201.4.3"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.852Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns1"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.859Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns1", "stdout": "tls://8.8.4.4"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.859Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns2"}
Thu May 26 13:36:43 2022 daemon.info mosdns[26105]: 2022-05-26T05:36:43.867Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns2", "stdout": "tls://9.9.9.9"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.059Z	info	v3/main.go:157	current working directory: /etc/mosdns/
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.060Z	info	v3/main.go:223	mosdns ver: cee9e6d
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.060Z	info	v3/main.go:224	arch: mipsle, os: linux, go: go1.18.1
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.060Z	info	coremain/run.go:65	loading config	{"file": "./def_config.yaml"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.061Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.loglv"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.069Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.loglv", "stdout": "error"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.070Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.logfile"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.078Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.logfile", "stdout": "/dev/null"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.078Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.085Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port", "stdout": "5335"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.086Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.093Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.listen_port", "stdout": "5335"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.094Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 0"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.193Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 0", "stdout": "218.201.17.2"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.194Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 1"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.293Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 1", "stdout": "218.201.4.3"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.294Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns1"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.301Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns1", "stdout": "tls://8.8.4.4"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.302Z	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns2"}
Thu May 26 13:36:52 2022 daemon.info mosdns[26164]: 2022-05-26T05:36:52.310Z	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.remote_dns2", "stdout": "tls://9.9.9.9"}
Thu May 26 13:36:53 2022 daemon.info procd: Instance mosdns::mosdns s in a crash loop 6 crashes, 3 seconds since last crash

> 
mosdns启动后，过几十秒钟，提示未启动，无法上网了。
git pull以后编译就出现问题了，今天。

**Comment by blueveryday** [comment]
我采用默认配置文件，mosdns就无法启动。
选择自定义配置文件。（啥也没有修改）
mosdns就能成功启动并使用了。
好奇怪。

**Comment by blueveryday** [comment]
2022-05-26T09:28:22.401Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_is_local_domain: failed to load entry ext:/usr/share/v2ray/geosite.dat:apple-cn: can not find category apple-cn in /usr/share/v2ray/geosite.dat"}
2022-05-26T09:28:30.763Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_is_local_domain: failed to load entry ext:/usr/share/v2ray/geosite.dat:apple-cn: can not find category apple-cn in /usr/share/v2ray/geosite.dat"}
2022-05-26T09:28:38.966Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_is_local_domain: failed to load entry ext:/usr/share/v2ray/geosite.dat:apple-cn: can not find category apple-cn in /usr/share/v2ray/geosite.dat"}
2022-05-26T09:28:46.672Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_is_local_domain: failed to load entry ext:/usr/share/v2ray/geosite.dat:apple-cn: can not find category apple-cn in /usr/share/v2ray/geosite.dat"}
2022-05-26T09:28:54.657Z	fatal	coremain/run.go:37	failed to load config	{"error": "failed to init plugin query_is_local_domain: failed to load entry ext:/usr/share/v2ray/geosite.dat:apple-cn: can not find category apple-cn in /usr/share/v2ray/geosite.dat"}

**Comment by blueveryday** [comment]
去掉这句代码，就可以正常使用了，用def配置文件。
- "ext:/usr/share/v2ray/geosite.dat:apple-cn"

**Comment by IrineSistiana** [comment]
原版 geosite.dat 不带 `apple-cn` 这个 tag。只有那个加强版带。

cc @QiuSimons

**Comment by sbwml** [comment]
源码 revert 这个提交  https://github.com/QiuSimons/openwrt-mos/pull/105/commits/9c3b612145a611109fa972a9ab317ae2f492e1f3

乱PR 的后果

**Comment by sbwml** [comment]
不对，不对，https://github.com/QiuSimons/openwrt-mos/blob/master/v2ray-geodata/Makefile#L27

是你的问题，这个仓库里的geodata 是包含apple-cn 类别的，你应该是使用了其它地方的geodata数据库了
