### ISSUE TITLE
上游SSRP+的DNS解析方式变更，DNS设置助手需要相应更改

### ISSUE THREAD

**Issue by BestHH** [QiuSimons/openwrt-mos#109]

**Comment by QiuSimons** [comment]
需要改啥？有啥不兼容的？？？
测试下来没有任何要改的地方，有问题说问题，不擅长算命

**Comment by BestHH** [comment]
> 需要改啥？有啥不兼容的？？？ 测试下来没有任何要改的地方，有问题说问题，不擅长算命

我的问题，没描述清楚。
![image](https://user-images.githubusercontent.com/37528193/173998837-2673f859-a081-40c9-9a11-401f646a29bb.png)
pdnsd已移除，是否应该变更为dns2tcp
