### ISSUE TITLE
最新V4版的两个问题，请教下大佬。

### ISSUE THREAD

**Issue by Liang-Cao** [QiuSimons/openwrt-mos#113]
第一个就是默认配置文件：更新以后选默认配置文件，每次启动就重置配置文件内容。自己改的一些配置就会消失。以前老版本改默认配置文件，可以实现自定义配置在luci界面改一些配置和看日志，新版本完全不能了。
第二个就是，v4改了读取文件的逻辑。我自己设置了一个blacklist列表，在日志里看，加载不全。而且运行的时候进行匹配有问题，自己设定的列表虽然读取了部分，好像也不会被匹配。不知道是不是我自己设置问题，请大佬们指教一下。

**Comment by IrineSistiana** [comment]
v4版我还没有开发完。现在是alpha阶段。会继续有不兼容的变化。

不建议日常用。

**Comment by Liang-Cao** [comment]
> v4版我还没有开发完。现在是alpha阶段。会继续有不兼容的变化。
> 
> 不建议日常用。

哈哈，我也是想试试。不过新配置文件弄好了的话，精简很多，

**Comment by Liang-Cao** [comment]
> 有自定义需求请使用自定义配置，默认配置本就是不可调整的
感谢大佬回复，默认配置的问题我明白一些了，上游取消引用了是不好弄了。那自己加进去列表不会被匹配到，不知道大佬能不能试一试。我就是在whitelist后面加了一个自定义的blacklist，列表里的用forward_remote解析。试了很多次没有生效。谢谢了

**Comment by QiuSimons** [comment]
你看一下你的配置文件是不是有问题吧，应该是没影响的

**Comment by Liang-Cao** [comment]
> 你看一下你的配置文件是不是有问题吧，应该是没影响的

配置文件没问题，我自己试了。现在有个现象是放到外部文件就会匹配失败，我用debug日志看了下，即使是内置的白名单也匹配不到。如果直接写在匹配器下面就不用外部文件就能匹配到，像这样。
  - tag:                   "query_is_blacklist_domain"
    type:                  query_matcher
    args:
      domain:
            - "dnsleaktest.com"
            - "huluim.com"
            - "hbogo.com"
            - "ipleak.net"
            - "2ip.io"
            - "browserleaks.com"
            - "browserleaks.org"
            - "whrq.net"
            - "whoer.net"
            - "provider:blacklist"
![image](https://user-images.githubusercontent.com/64605492/174746664-6781a271-c24d-42f9-a697-a7fa1fb699bb.png)

![image](https://user-images.githubusercontent.com/64605492/174745713-8ddba84d-5a7e-4c61-bc74-bdae404d6e46.png)

**Comment by Liang-Cao** [comment]
![image](https://user-images.githubusercontent.com/64605492/174747087-28a25e89-ff1b-4360-bd20-584ee6017f21.png)

**Comment by QiuSimons** [comment]
我拿白名单功能测试了下，log开到debug，看到是能匹配到的

**Comment by Liang-Cao** [comment]
> 我拿白名单功能测试了下，log开到debug，看到是能匹配到的

感谢大佬测试，新版本的没问题了，已经解决。顺便新版还有个问题咨询下，就是开info日志看到的警报基本都是 use of closed network connection这种，不知道什么问题引起的，之前v3的时候好像报的没这么频繁。是不是fastfoward里面的doh和dot用的域名形式引起的呢，但是我都加了dile_addr.
![image](https://user-images.githubusercontent.com/64605492/176613396-de2b6c95-83d5-4fc9-855d-3d90c3e01a80.png)

![image](https://user-images.githubusercontent.com/64605492/176613572-76abe47a-db7a-4eba-a495-e93ab4dd186f.png)

**Comment by Liang-Cao** [comment]
我知道问题了，是clash的延迟测速。我一点测速就一大片 use of closed network connection.
![image](https://user-images.githubusercontent.com/64605492/176691767-c43b8950-60b8-452a-834f-f0360d2cfc3e.png)
![image](https://user-images.githubusercontent.com/64605492/176691896-c76b8c11-c9ff-4325-9192-a7e95d0b37f6.png)
