### ISSUE TITLE
编译时报mosdns_neo依赖找不到

### ISSUE THREAD

**Issue by lonelysoul** [QiuSimons/openwrt-mos#118]
uci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist

影响使用么

**Comment by xcf262352133** [comment]
一样的情况，会编译失败。

**Comment by xcf13363175** [comment]
一样的情况，编译出错。pkg name不能用下划线

**Comment by lisonglin980** [comment]
+1 缺mosdns_neo依赖导致最后编译失败
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency mosdns_neo for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-mosdns-zh-cn:
 *      mosdns_neo
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.

**Comment by lisonglin980** [comment]
BuildPackage 变量
PKG_*定义了软件包相关的一些基本信息，如下所示：
PKG_NAME -包的名称,可以通过menuconfig和ipkg看到。 不要使用下划线。
PKG_VERSION -下载的或者自己写的软件包的版本号（必须）。
