### ISSUE TITLE
最新的mosdns启动不了

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [QiuSimons/openwrt-mos#121]
Mon Jun 27 00:30:56 2022 daemon.info mosdns[21363]: 2022-06-27T00:30:56.972+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:30:57 2022 daemon.err mosdns[21363]: 2022-06-27T00:30:57.187+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:02 2022 daemon.info mosdns[22087]: 2022-06-27T00:31:02.715+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:31:02 2022 daemon.err mosdns[22087]: 2022-06-27T00:31:02.920+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:08 2022 daemon.info mosdns[22135]: 2022-06-27T00:31:08.473+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:31:08 2022 daemon.err mosdns[22135]: 2022-06-27T00:31:08.680+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:14 2022 daemon.info mosdns[22165]: 2022-06-27T00:31:14.218+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:31:14 2022 daemon.err mosdns[22165]: 2022-06-27T00:31:14.428+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:19 2022 daemon.info mosdns[22196]: 2022-06-27T00:31:19.982+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:31:20 2022 daemon.err mosdns[22196]: 2022-06-27T00:31:20.184+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:25 2022 daemon.info mosdns[22246]: 2022-06-27T00:31:25.733+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:31:25 2022 daemon.err mosdns[22246]: 2022-06-27T00:31:25.934+0800	fatal	coremain/run.go:102	mosdns exited	{"error": "failed to init plugin #13, cannot build sequence: invalid cmd at #1: can not find execuable _single_flight"}
Mon Jun 27 00:31:26 2022 daemon.info procd: Instance mosdns::mosdns s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by xiangfeidexiaohuo** [comment]
插件自己的日志输出也看不到呢，保存应用，能存活几秒，然后就停止了。

**Comment by xiangfeidexiaohuo** [comment]
Mon Jun 27 00:35:25 2022 daemon.err nmbd[6824]: [2022/06/27 00:35:25.159086,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Mon Jun 27 00:35:25 2022 daemon.err nmbd[6824]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.2 for name WORKGROUP<1d>.
Mon Jun 27 00:35:25 2022 daemon.err nmbd[6824]:   This response was from IP 192.168.2.202, reporting an IP address of 192.168.2.202.
Mon Jun 27 00:40:27 2022 daemon.err nmbd[6824]: [2022/06/27 00:40:27.544952,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Mon Jun 27 00:40:27 2022 daemon.err nmbd[6824]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.2 for name WORKGROUP<1d>.
Mon Jun 27 00:40:27 2022 daemon.err nmbd[6824]:   This response was from IP 192.168.2.202, reporting an IP address of 192.168.2.202.
Mon Jun 27 00:45:34 2022 daemon.err nmbd[6824]: [2022/06/27 00:45:34.530884,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
Mon Jun 27 00:45:34 2022 daemon.err nmbd[6824]:   query_name_response: Multiple (2) responses received for a query on subnet 192.168.2.2 for name WORKGROUP<1d>.
Mon Jun 27 00:45:34 2022 daemon.err nmbd[6824]:   This response was from IP 192.168.2.202, reporting an IP address of 192.168.2.202.
Mon Jun 27 00:49:01 2022 daemon.err uhttpd[2136]: Collected errors:
Mon Jun 27 00:49:01 2022 daemon.err uhttpd[2136]:  * resolve_conffiles: Existing conffile /etc/config/mosdns is different from the conffile in the new package. The new conffile will be placed at /etc/config/mosdns-opkg.
Mon Jun 27 00:49:01 2022 daemon.err uhttpd[2136]:  * resolve_conffiles: Existing conffile /etc/mosdns/rule/whitelist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/whitelist.txt-opkg.
Mon Jun 27 00:49:01 2022 daemon.err uhttpd[2136]:  * resolve_conffiles: Existing conffile /etc/mosdns/rule/serverlist.txt is different from the conffile in the new package. The new conffile will be placed at /etc/mosdns/rule/serverlist.txt-opkg.
Mon Jun 27 00:49:35 2022 daemon.info mosdns[8339]: 2022-06-27T00:49:35.479+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:49:35 2022 daemon.err mosdns[8339]: 2022-06-27T00:49:35.480+0800	fatal	coremain/run.go:98	failed to parse config file	{"error": "1 error(s) decoding:\n\n* 'servers[0]' has invalid keys: listener"}
Mon Jun 27 00:49:40 2022 daemon.info mosdns[8420]: 2022-06-27T00:49:40.889+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:49:40 2022 daemon.err mosdns[8420]: 2022-06-27T00:49:40.889+0800	fatal	coremain/run.go:98	failed to parse config file	{"error": "1 error(s) decoding:\n\n* 'servers[0]' has invalid keys: listener"}
Mon Jun 27 00:49:46 2022 daemon.info mosdns[8493]: 2022-06-27T00:49:46.285+0800	info	coremain/run.go:77	working directory changed	{"path": "/etc/mosdns/"}
Mon Jun 27 00:49:46 2022 daemon.err mosdns[8493]: 2022-06-27T00:49:46.285+0800	fatal	coremain/run.go:98	failed to parse config file	{"error": "1 error(s) decoding:\n\n* 'servers[0]' has invalid keys: listener"}

**Comment by xcf262352133** [comment]
4.0.0版中_single_flight插件已经删掉了

**Comment by kbrx93** [comment]
同 IrineSistiana/mosdns/#396，需要在配置文件中去掉 _single_flight 或者下载 V4-alpha 版

**Comment by lisonglin980** [comment]
> 同 [#396](https://github.com/IrineSistiana/mosdns/issues/396)，需要在配置文件中去掉 _single_flight 或者下载 V4-alpha 版

单独去掉single_flight那一段配置文件还是运行不起来，直接https://op.dllkids.xyz/packages/x86_64/下载6.17的mosdns和luci用吧，V4配置文件还是有点问题
