### ISSUE TITLE
#125修复之后问题补充，编译依然报错，错误相同

### ISSUE THREAD

**Issue by xnxy2012** [QiuSimons/openwrt-mos#126]
Configuring ip6tables-mod-nat.
 * pkg_hash_check_unresolved: cannot find dependency mosdns-neo for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-mosdns-zh-cn:
 * 	mosdns-neo
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255

临时解决方法：将mosdns及luci文件夹里makefile文件中所有关于mosdns-neo修改为mosdns，编译可以通过，程序正常运行，编译源码为lean最新源码5.15内核

**Comment by yaof2** [comment]
同样问题。更名后无法编译

**Comment by QiuSimons** [comment]
测试后没有问题，建议检查源码拉取是否完整

**Comment by yaof2** [comment]
依旧编译通不过。卡在mosdns这里。

**Comment by QiuSimons** [comment]
检查lean源码是否包含mosdns的package，如果有，请删除并替换这边的版本

**Comment by plasmolysis369** [comment]
用lede源码的单独拉luci就可以了，package里自带mosdns，毕竟人家的源码是按照openwrt官方主线写完自己用的

**Comment by starxu1971** [comment]
在线编译应该怎么弄呢。

**Comment by lisonglin980** [comment]
> 在线编译应该怎么弄呢。



> 用lede源码的单独拉luci就可以了，package里自带mosdns，毕竟人家的源码是按照openwrt官方主线写完自己用的

只把.\feeds\packages\net\mosdns文件夹删了，编译还是报错
make[3]: *** [Makefile:93: /home/lee/immortalwrt/build_dir/target-x86_64_musl/mosdns-48c2570/.built] Error 127
make[3]: Leaving directory '/home/lee/immortalwrt/feeds/kenzo/mosdns'
time: package/feeds/kenzo/mosdns/compile#1.31#0.41#0.81
    ERROR: package/feeds/kenzo/mosdns failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/mosdns/compile] Error 1
make[2]: Leaving directory '/home/lee/immortalwrt'
make[1]: *** [package/Makefile:110: /home/lee/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lee/immortalwrt'
make: *** [/home/lee/immortalwrt/include/toplevel.mk:230: world] Error 2

**Comment by xnxy2012** [comment]
> > 在线编译应该怎么弄呢。
> 
> > 用lede源码的单独拉luci就可以了，package里自带mosdns，毕竟人家的源码是按照openwrt官方主线写完自己用的
> 
> 只把.\feeds\packages\net\mosdns文件夹删了，编译还是报错 make[3]: *** [Makefile:93: /home/lee/immortalwrt/build_dir/target-x86_64_musl/mosdns-48c2570/.built] Error 127 make[3]: Leaving directory '/home/lee/immortalwrt/feeds/kenzo/mosdns' time: package/feeds/kenzo/mosdns/compile#1.31#0.41#0.81 ERROR: package/feeds/kenzo/mosdns failed to build. make[2]: *** [package/Makefile:116: package/feeds/kenzo/mosdns/compile] Error 1 make[2]: Leaving directory '/home/lee/immortalwrt' make[1]: *** [package/Makefile:110: /home/lee/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/lee/immortalwrt' make: *** [/home/lee/immortalwrt/include/toplevel.mk:230: world] Error 2

删错了，目标位置在lede/package/feeds/packages/mosdns，把modns文件夹整个删除。
cd lede/package/feeds/packages
rm -rf modns

**Comment by lisonglin980** [comment]
> 

lede/package/feeds/packages/里面没有mosdns文件夹哟

**Comment by lisonglin980** [comment]
> 
删了lede/package/feeds/packages/mosdns文件之后报错变了
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency mosdns-neo for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-mosdns-zh-cn:
 *      mosdns-neo
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/lee/immortalwrt'
make[1]: *** [package/Makefile:111: /home/lee/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/lee/immortalwrt'
make: *** [/home/lee/immortalwrt/include/toplevel.mk:230: world] Error 2

**Comment by lonelysoul** [comment]
> 


> 检查lean源码是否包含mosdns的package，如果有，请删除并替换这边的版本，同理geodata https://github.com/coolsnowwolf/packages/tree/master/net/mosdns 事实证明，是有的
> 
> 说点题外话，如果语气重了，还请谅解。 采用-neo扩展名，就是为了防止某些无脑用户，不完整拉取本源码，反馈各种无效issue（包括这个issue 说实话，不检查本地问题，不看log，无脑反馈，是一种浪费双方时间的行为 之前有人反馈geodata:apple不可用，也是因为没用这里的geodata，而是openwrt源码里自带的 每天看到这种问题很烦，所以感觉neo了，用不了的自然就不用了，用的了的说明至少有基础，不会反馈无效bug 毕竟这个app是自用为主，分享出来不是为了给作者自己添堵的 您说是吧？


大佬能不能给个操作指引，对官方版本和lede版本；
没有这个操作说明，就会有各种各样取一部分代码去编译的。

**Comment by xnxy2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by 4thanks** [comment]
> github在线编译lede源码可以在编译前删除lean源码下luci-app-mosdns的插件及packages包，然后拉取加入，避免冲突 rm -rf feeds/luci/applications/luci-app-mosdns rm -rf feeds/packages/net/mosdns rm -rf feeds/packages/net/v2ray-geodata git clone https://github.com/QiuSimons/openwrt-mos.git package/openwrt-mos 还有，由于ssrplus中的与mosdns使用的v2ray-geodata源码不一致，还需要删除ssrplus中的v2ray-geodata文件，最好替换一下

github在线编译用[immortalwrt 21.03](https://github.com/immortalwrt/immortalwrt)还是编译失败，请问是什么原因？
```bash
make[3] -C package/network/services/shellsync compile
make[3] -C package/openwrt-mos/mosdns compile
make[3] -C package/system/mtd compile
make[3] -C package/system/urngd compile
make[3] -C package/utils/busybox compile
    ERROR: package/openwrt-mos/mosdns failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/runner/work/ctc-openwrt/ctc-openwrt/openwrt/include/toplevel.mk:230: world] Error 1
make[1]: Entering directory '/home/runner/work/ctc-openwrt/ctc-openwrt/openwrt'
make[2]: Entering directory '/home/runner/work/ctc-openwrt/ctc-openwrt/openwrt'
make[3]: Entering directory '/home/runner/work/ctc-openwrt/ctc-openwrt/openwrt/target/linux'
make[4]: Entering directory '/home/runner/work/ctc-openwrt/ctc-openwrt/openwrt/target/linux/ipq40xx'
rm -f /home/runner/work/ctc-openwrt/ctc-openwrt/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.4.230/localversion
```

**Comment by xnxy2012** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到，我会尽快给您回复。
