### ISSUE TITLE
ssrp切换节点后，gfw_list.conf里的内容会自动清除！

### ISSUE THREAD

**Issue by zxlhhyccc** [QiuSimons/openwrt-mos#129]
为何这一行https://github.com/QiuSimons/openwrt-mos/blob/master/luci-app-mosdns/root/etc/init.d/mosdns#L125 要清除：gfw_list.conf里的内容？！

**Comment by QiuSimons** [comment]
看tm的过往issue

**Comment by zxlhhyccc** [comment]
> 看tm的过往issue

啥意思？
