### ISSUE TITLE
ssh可以启动，luci界面无法启动问题

### ISSUE THREAD

**Issue by XiaoPengMei** [QiuSimons/openwrt-mos#131]
具体现象就是 luci 界面里点击保存并应用跳一下启动之后就宕了
对了 luci 界面默认配置也无法启动成功
我对比默认配置，把servers相关整合到了 main_server 里，依旧无法解决问题
ssh 执行 mosdns start 可以正常启动并运行
大佬我也没找到具体日志在哪里，您看需要什么，我给您发

**Comment by XiaoPengMei** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/16916029/178438583-7d767ba7-fcc1-4acb-aab1-25843f49298c.png">
刚刚发现我的 mosdns 命令和 init.d 中调用的出现了一些出入
我尝试修改为
<img width="485" alt="image" src="https://user-images.githubusercontent.com/16916029/178445216-14c00978-9727-46c6-952c-39ac1b14626b.png">
成功启动，不知道是什么版本问题，虽然解决了，大佬您看下再关闭吧

**Comment by QiuSimons** [comment]
大概率是混用老的mosdns运行文件和新的luci导致的
