### ISSUE TITLE
使用自定义配置的时候， 日志不显示

### ISSUE THREAD

**Issue by ibinlike** [QiuSimons/openwrt-mos#134]
使用最新的版本自编译了OpenWRT。 

使用内置预设的时候， 日志显示正常。 

但是在使用自定义配置的时候， 日志不显示。 但日志确实有产生， 能通过ssh登录到软路由， 查看tmp/mosdns.txt.

期望的正常反应：

日志正常显示在日志栏。 

#问题解决了， 不好意思。

**Comment by RongMoM** [comment]
请问一下是怎么解决的呢，我也有一样的问题

**Comment by ibinlike** [comment]
数据库更新那里， 勾上"启用配置文件同步“。
