### ISSUE TITLE
LXC 环境下 MOS  数据库无法更新，麻烦大佬进来对个鸡鸡。

### ISSUE THREAD

**Issue by love768952693** [QiuSimons/openwrt-mos#137]
前言：
大佬，我知道你每天日李万鸡，要维护X86的固件，但是我还是要报告。

经过：
在LXC环境下，装了openwrt 	分支: 22.03.2，内核: 5.15.74，装上心爱的 mos。（因为以前X86用这个用习惯了）

症状：
不下载任何数据文件，现数据库无法更新。

排查：
反馈问题肯定要拿东西，所以各种看日志，从系统日志，到内核日志，再到mos的log，包括切换调试和错误等等日志mos，都没有痕迹，

**Comment by QiuSimons** [comment]
抱歉，没有测试环境，忙猜宿主机和容器的通信相关问题，或者容器环境问题
