### ISSUE TITLE
突然一堆警告~有影响吗？

### ISSUE THREAD

**Issue by Pacio** [QiuSimons/openwrt-mos#139]
![image](https://user-images.githubusercontent.com/6836705/204317922-73c5a381-c46c-4b91-b27f-e6d2a4a85d56.png)
![image](https://user-images.githubusercontent.com/6836705/204318010-835c7769-99e8-4aa0-8be7-e48c00b896bd.png)

**Comment by daiaji** [comment]
@IrineSistiana
