### ISSUE TITLE
mosdns-neo 啥玩意？

### ISSUE THREAD

**Issue by daiaji** [QiuSimons/openwrt-mos#140]
新的mosdns？

**Comment by QiuSimons** [comment]
当时v3到v4的时候配置文件有兼容性问题，怕用户编译的时候直接用别的仓库里的mosdns编译，然后出问题，故意做的名字上的区分
同样的，上游很快就会更新v5，所以会保留这个刻意的差异化

**Comment by daiaji** [comment]
我要重写配置吗？
