### ISSUE TITLE
我打算重新把shell脚本里的那一堆硬编码的玩意解耦。

### ISSUE THREAD

**Issue by daiaji** [QiuSimons/openwrt-mos#141]
感觉晚弄不如早弄，我有时间就搞一下吧。
这感觉不搞，迟早变屎山。
虽然现在那些为了复用而整出来的函数，和意味不明的函数名。
看起来就蛮吓人了。

**Comment by daiaji** [comment]
目前想到一个点子，就是由于那个类库脚本如果声明全局变量的话，由于几乎所有脚本都调用过那个类库脚本，硬编码的DNS之类的，应该改成变量全写在那里。

在开头就声明变量也还蛮常见的吧。

**Comment by QiuSimons** [comment]
可以的，大佬加油！

**Comment by daiaji** [comment]
OK了。

**Comment by QiuSimons** [comment]
大佬辛苦了，各项功能您run test过了么？
pr咱先合并了，但最近没啥时间仔细搞，如果大佬后面发现有啥bug，还请继续pr，万分感谢

**Comment by daiaji** [comment]
set.sh那一堆命令能用&丢到后台并行化吗？

**Comment by QiuSimons** [comment]
> set.sh那一堆命令能用&丢到后台并行化吗？

看了下，理论上应该可以的

**Comment by daiaji** [comment]
要不你动手？
我在捣鼓PE。

**Comment by QiuSimons** [comment]
> 要不你动手？
> 我在捣鼓PE。

先缓缓，刚升级到v5的核心，先测试一段时间，稳定了再搞景上添花的事情

**Comment by daiaji** [comment]
快进到摸了。

**Comment by daiaji** [comment]
历时一年多，终于搞完了。
