### ISSUE TITLE
mosdns v5的配置文件大改了，默认使用v4的配置将无法启动

### ISSUE THREAD

**Issue by firkerword** [QiuSimons/openwrt-mos#147]
dat文件好像不支持了
IrineSistiana大佬说年后才开始写通用的配置文件

**Comment by NEARWN** [comment]
![670bd4e43b9d7cf28b85c46deb26bb7](https://user-images.githubusercontent.com/59085578/213589651-6075371a-95f2-4876-9cbb-85e91ce88f48.jpg)
最近确实有问题

**Comment by KevinMX** [comment]
https://github.com/QiuSimons/openwrt-mos/commit/792dfd44044dc6a1e89419c2e400edaf07b11bc6

**Comment by lededev** [comment]
配置文件也就改了这么几行而已，算不上大改，建议根据mosdns执行文件版本进行一下适配，支持v4和v5.

https://github.com/IrineSistiana/mosdns/commit/2310a446303f8809818acc8488fd25adb2b87424

**Comment by KevinMX** [comment]
> 配置文件也就改了这么几行而已，算不上大改

mosdns v5 移除/改动了很多功能。建议查看 release log。

**Comment by QiuSimons** [comment]
已经适配了v5
