### ISSUE TITLE
v2ray-geodata 好像可以这样在v5上复用

### ISSUE THREAD

**Issue by qingtian110** [QiuSimons/openwrt-mos#148]
直接解压txt出来读取，不需要依赖网络下载。但是没有ipk文件 尚未得到测试
https://github.com/sbwml/luci-app-mosdns/commit/4671c0823048207f34e24775b84841604d6c30cf

**Comment by qingtian110** [comment]
https://github.com/sbwml/luci-app-mosdns/commit/5597a6c3069ea22536c11ceb6e5572546c803a89

**Comment by QiuSimons** [comment]
解包的方式也不是复用，而且引入了新的依赖，没价值
