### ISSUE TITLE
luci-app-mosdns 编译失败

### ISSUE THREAD

**Issue by davidtall** [QiuSimons/openwrt-mos#153]
make menuconfig 提示 luci-app-mosdns/Makefile' has a dependency on 'mosdns-v5', which does not exist
 编译失败
然后我把 luci-app-mosdns/Makefile 里面的LUCI_DEPENDS mosdns-v5 改成 mosdns，编译成功 ,用的是immortalwrt 源码

**Comment by QiuSimons** [comment]
see #126
