### ISSUE TITLE
关于启动脚本的小功能请求

### ISSUE THREAD

**Issue by realconnor** [QiuSimons/openwrt-mos#16]
首先，辛苦作者的工作😄 

如题，不知道能否在设置中新增一个开关，以控制是否接管`dnsmasq`上游？

目前启动脚本是直接通过`prepare_setting`函数直接设置好了`dnsmasq`上游服务器，甚至`/etc/config/network`的 DNS。但是有些代理程序，比如 Clash 需要接管 DNS 才能「正常」工作，与之冲突。将 mosdns 作为 ADH 的上游也有类似的问题。

**Comment by QiuSimons** [comment]
要不你给个pr？调用prepare和reset前加个判断应该就行了

**Comment by realconnor** [comment]
没问题，我等吧，等完善了可以把现在的ADH->chinadns-ng->smartdns套娃换了😂，尤其smartdns，bug真是茫茫多

**Comment by QiuSimons** [comment]
编译测试下吧
