### ISSUE TITLE
编译正常，但登录Op后Luci报错

### ISSUE THREAD

**Issue by FunnyFly-ZW** [QiuSimons/openwrt-mos#165]
显示如下：
/usr/lib/lua/luci/controller/mosdns.lua:28: attempt to call upvalue 'check_config_file' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/mosdns.lua:28: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:585: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:251: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

**Comment by daiaji** [comment]
```lua
local function check_config_file()
    return nixio.fs.access("/etc/config/mosdns")
end
```
此函数只有一个作用。
检测`/etc/config/mosdns`是否存在。
我猜你的`/etc/config/mosdns`不存在。

**Comment by FunnyFly-ZW** [comment]
> ```lua
> local function check_config_file()
>     return nixio.fs.access("/etc/config/mosdns")
> end
> ```
> 
> 此函数只有一个作用。 检测`/etc/config/mosdns`是否存在。 我猜你的`/etc/config/mosdns`不存在。

感谢

**Comment by FunnyFly-ZW** [comment]
> ```lua
> local function check_config_file()
>     return nixio.fs.access("/etc/config/mosdns")
> end
> ```
> 
> 此函数只有一个作用。 检测`/etc/config/mosdns`是否存在。 我猜你的`/etc/config/mosdns`不存在。

我检查了/etc/config/mosdns，是存在的，文件内容和源码一致
另外/usr/bin/mosdns的二进制文件也是在的
还是出现这个错误
大佬能帮忙看下吗，https://github.com/FunnyFly-ZW/OpenWRT-CI/releases，第一个

**Comment by daiaji** [comment]
老实说这个包只保证在主线能用，其他的openwrt但凡版本旧点，不工作很正常，我也无意修正旧版本的兼容性问题。

**Comment by qingtian110** [comment]
> 显示如下： /usr/lib/lua/luci/controller/mosdns.lua:28: attempt to call upvalue 'check_config_file' (a nil value) stack traceback: /usr/lib/lua/luci/controller/mosdns.lua:28: in function 'v' /usr/lib/lua/luci/dispatcher.lua:585: in function 'createtree' /usr/lib/lua/luci/dispatcher.lua:251: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>

#163 之后，这个 luci 已经废了。外加 #167 。。。。

你怎么不用这个版本  https://github.com/sbwml/luci-app-mosdns   这个经过 时间和用户检阅过的

**Comment by daiaji** [comment]
> > 显示如下： /usr/lib/lua/luci/controller/mosdns.lua:28: attempt to call upvalue 'check_config_file' (a nil value) stack traceback: /usr/lib/lua/luci/controller/mosdns.lua:28: in function 'v' /usr/lib/lua/luci/dispatcher.lua:585: in function 'createtree' /usr/lib/lua/luci/dispatcher.lua:251: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>
> 
> #163 之后，这个 luci 已经废了。外加 #167 。。。。
> 
> 你怎么不用这个版本 https://github.com/sbwml/luci-app-mosdns 这个经过 时间和用户检阅过的

sbwml本人也无意PR，而且本项目一直也不在意兼容性，在主线openwrt能跑就无所谓，基本上只有你自己愿意修兼容，才有得搞的样子。

**Comment by qingtian110** [comment]
openwrt 从未放弃过对 lua 的支持，所以不存在兼容不兼容的说法。在 openwrt 上能正常跑的 lua，lede 一样可以，它对标 18.06。唯一有问题的只有被魔改的OP --> QSDK，因为 QSDK functions 自身存在问题。不过这个东西可以忽略，因为用的人太少。

主要是搞不懂为什么会提这样的PR，看 commit 说明是代码规范，但事实上你如果去看 openwrt 现有的 lua luci-app，你会发现这 PR 完全不规范，甚至炸裂的地方特别多。

**Comment by qingtian110** [comment]
针对 op主线的lua兼容来讲，这也不符合 ucode 的规范。。。。

**Comment by daiaji** [comment]
> openwrt 从未放弃过对 lua 的支持，所以不存在兼容不兼容的说法。在 openwrt 上能正常跑的 lua，lede 一样可以，它对标 18.06。唯一有问题的只有被魔改的OP --> QSDK，因为 QSDK functions 自身存在问题。不过这个东西可以忽略，因为用的人太少。
> 
> 主要是搞不懂为什么会提这样的PR，看 commit 说明是代码规范，但事实上你如果去看 openwrt 现有的 lua luci-app，你会发现这 PR 完全不规范，甚至炸裂的地方特别多。

https://forum.openwrt.org/t/can-i-use-lua-to-write-init-scripts/189793/3?u=daiaji

**Comment by FunnyFly-ZW** [comment]
大佬们别争了，我知道这个仓库适合官方源码，不适合大雕的lede了。其实只是好奇和sbwml那个用起来有什么不同想试试看而已…
