### ISSUE TITLE
更新数据库无反应

### ISSUE THREAD

**Issue by Jan20th9e** [QiuSimons/openwrt-mos#47]
使用immortalwrt 18.06-k5.4分支添加插件编译后，在luci界面点击“检查并更新”数据库后无反应。如果使用命令手动执行mosupdater.sh则可以正常更新数据库。

**Comment by QiuSimons** [comment]
不一定兼容luci18，我自己的使用环境是luci21

**Comment by Jan20th9e** [comment]
> 不一定兼容luci18，我自己的使用环境是luci21

能否做下兼容，麻烦的话我干脆切换到immortalwrt的21.02分支？

**Comment by QiuSimons** [comment]
检查了一下，是兼容的，很可能是你自己的问题（

**Comment by Jan20th9e** [comment]
> 检查了一下，是兼容的，很可能是你自己的问题（

https://github.com/immortalwrt/packages/tree/openwrt-18.06/net/mosdns
请问源码候选了luci但是默认编译了这个文件夹和二进制有无关系，而且这个编译出来默认也是使用imm的那个配置文件，我是用files大法把你的config.yaml替换掉默认的。

**Comment by QiuSimons** [comment]
破案了…..请替换本源码……

**Comment by Pacio** [comment]
如果不使用dns过滤广告功能还用开启数据库自动更新吗?
