### ISSUE TITLE
与ssr-plus搭配时遇到的启动问题

### ISSUE THREAD

**Issue by jliveusa** [QiuSimons/openwrt-mos#48]
重启openwrt后，会出现ssr-plus成功运行，但无法fq，重启ssr-plus可解决。怀疑与启动顺序有关~

**Comment by QiuSimons** [comment]
Q1：什么设备
Q2：如果mosdns的启动顺序改成89，重启设备会有改善么？

**Comment by jliveusa** [comment]
双网卡软路由，尝试多次更改了mosdns和ssr-plus的先后启动顺序，没有改善，还是要手动重启ssr-plus

**Comment by QiuSimons** [comment]
试过45么

**Comment by jliveusa** [comment]
没试过，现在尝试一下

**Comment by jliveusa** [comment]
又失败了

**Comment by QiuSimons** [comment]
你确定你改对了么（重新重链了lint.d了么….

**Comment by jliveusa** [comment]
重链了的

**Comment by QiuSimons** [comment]
截图ssrp页面以及mos页面，我看下你的设置

**Comment by jliveusa** [comment]
log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - _single_flight
        - main_sequence
      server:
        - protocol:        udp
          addr:            '127.0.0.1:5335'
        - protocol:        tcp
          addr:            '127.0.0.1:5335'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _end
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _end
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback:   150
          always_standby:  true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tcp://119.29.29.29'
        - addr:            'tcp://223.5.5.5'


  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://8.8.4.4'
          idle_timeout:    60
        - addr:            'tls://1.0.0.1'
          idle_timeout:    60

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

**Comment by jliveusa** [comment]
![1](https://user-images.githubusercontent.com/42428798/147403394-7307db6a-535b-475f-995e-956c3cb4f91a.png)
![2](https://user-images.githubusercontent.com/42428798/147403396-51d30483-25c4-41c0-bfab-c38ad67c126c.png)

**Comment by QiuSimons** [comment]
晚点我调整一下启动逻辑吧

**Comment by QiuSimons** [comment]
试试看吧，记得别留残余修改（你之前改过的init之类的
