### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by Jan20th9e** [QiuSimons/openwrt-mos#49]
前几天反映的更新数据库无反应 这两天换了几个其他源码后依旧发现不行。折腾了两天后发现是依赖问题，因为我本身编译的插件不多，然后其他插件本来不依赖bash所以编译时也没加进去，手动加了bash后可以正常更新了，建议在luci的Makefile里把插件需要的依赖补全。。
另外发现插件的重定向DNS功能似乎有点问题，无论勾不勾选，都会作为dnsmasq的上游。

**Comment by QiuSimons** [comment]
重定向实测没问题的，依赖我一会儿加

**Comment by Jan20th9e** [comment]
> 重定向实测没问题的，依赖我一会儿加

那就奇了怪了。。我DNS重定向这个设置无论开关。dns转发里都会有127.0.0.1#5335。只有关闭插件才会恢复默认
