### ISSUE TITLE
[提议] luci 选项和配置解耦

### ISSUE THREAD

**Issue by IrineSistiana** [QiuSimons/openwrt-mos#52]
现在 luci 里的选项和配置文件耦合的挺厉害的。会让没经验的用户感到迷惑。用户改配置需要兼顾两边，一不小心就不能用了。

提议。完全解耦luci配置和用户自定义的配置。

我不了解 openwrt 所以这个提议是瞎想的。

内置一个配置模板，`config_inner.yaml`，对用户不可见。内有广告分流等逻辑然后配合 `${{}}` 和 uci 读取生成设置。然后提供像 是否启用预设配置，日志级别，监听地址，服务器地址，是否过滤广告等简单选项。

仍提供自定义配置文件 `config_user.yaml`。让用户自由配置。然后提供一个“是否启用自由配置”选项。

然后用主配置文件 `config.yaml`，用 `include:` 配合 `${{}}` 选择载入哪些配置。

这样就解耦合了。预设配置可以随意更新不会影响用户，用户自定义的配置也和预设配置无关。

有点像 luci-samba4-app。

**Comment by QiuSimons** [comment]
工程量感觉有点大，不过感觉改进逻辑已经清晰了，不过我太菜，可能得随缘那天实现了….
（我一直感觉有大多数有高级自定义需求的人，关掉几个开关，然后直接用luci里的config文件编辑应该就好了，所以其实很多功能设计都没怎么过脑子

**Comment by IrineSistiana** [comment]
之前想用 luci-chinadns 的源码魔改适配 mosdns。放弃了。。。。

感觉 `${{}}` 配合 uci 读 config 还行。单个 option 能直接读。遇见列表数据也能脚本生成 yaml 的 ['xxx1','xxx2','xxx3'] 格式一行解决。

就是 luci..... orz

**Comment by QiuSimons** [comment]
@IrineSistiana ${{}}里可以直接执行操作么比如uci 或者其他操作么？还是说必须包装成脚本啊

**Comment by IrineSistiana** [comment]
这个我没试过。反正 ${{}} 干的事是:

空格分隔里面的字符串。

第一个字符作为命令，后续的作为参数。调用。

**Comment by QiuSimons** [comment]
好的，那我实验一下叭

**Comment by IrineSistiana** [comment]
我在想要不 luci-app-mosdns 就实现一个 yaml 修改器。

分流去广告什么的。之前可以直接用 mosdns-cn。实现起来比 mosdns 干净省事的多。

**Comment by IrineSistiana** [comment]
其实可以把 mosdns-cn 合并在 mosdns。因为本来就是一个东西。

**Comment by QiuSimons** [comment]
我觉得叭 -cn其实存档了问题也不大，mosdns本身其实更直观，而且更容易定制

**Comment by IrineSistiana** [comment]
> 我觉得叭 -cn其实存档了问题也不大，mosdns本身其实更直观，而且更容易定制

确实 mosdns 可定制性 max。

突然想到。如果已经确定要用配置模板的话，用 ${{}} 替换不如直接写 bash 替换更灵活。

**Comment by IrineSistiana** [comment]
> 突然想到。如果已经确定要用配置模板的话，用 ${{}} 替换不如直接写 bash 替换更灵活。

openwrt 标配 busybox。可以 sed awk 一把梭。

**Comment by IrineSistiana** [comment]
samba4，配置模板 + sed awk 一把梭

https://github.com/openwrt/packages/blob/openwrt-21.02/net/samba4/files/samba.init

**Comment by QiuSimons** [comment]
972e065 应该ok了，还没测试，晚点测试完合并
