### ISSUE TITLE
编译到lede源码下无法启动

### ISSUE THREAD

**Issue by geryson911** [QiuSimons/openwrt-mos#59]
编译到lede源码下无法启动，之前的旧版本是可以的，希望能修复下

**Comment by Ozzy-hzy** [comment]
> 编译到lede源码下无法启动，之前的旧版本是可以的，希望能修复下

我1月14号编译的版本（lean源码+openwrt-mosdns）没问题，能够正常使用。
如果用的自定义配置，看看系统日志有没有报错，可能配置写错了
