### ISSUE TITLE
想知道doh的dns请求会不会走ssrplus的代理

### ISSUE THREAD

**Issue by Ozzy-hzy** [QiuSimons/openwrt-mos#60]
国外dns设置的是谷歌和cloudflare的doh服务器，向这两个dns服务器的请求会不会经过ssrplus代理，是否返回的ip是离节点较近的ip。

**Comment by QiuSimons** [comment]
首先，不是doh是dot，其次不是cloudflare是quad9和google dns。最后走代理的，你不放心就在ssrp强制代理那边加上8.8.4.4和9.9.9.9的ip呗

**Comment by Ozzy-hzy** [comment]
> 首先，不是doh是dot，其次不是cloudflare是quad9和google dns。最后走代理的，你不放心就在ssrp强制代理那边加上8.8.4.4和9.9.9.9的ip呗

我是用的自定义配置，设置的这是两个DOH，走代理那么返回的ip是离节点较近的ip吧，我对这里不太清楚

**Comment by QiuSimons** [comment]
是的，如果走代理的话
