### ISSUE TITLE
停止运行会自动禁止解析 IPv6 DNS 记录

### ISSUE THREAD

**Issue by Ozzy-hzy** [QiuSimons/openwrt-mos#61]
关闭mosdns后，发现DHCP/DNS，高级设置中的禁止解析 IPv6 DNS 记录被打勾了。

我觉得这个选项不要动比较好

**Comment by QiuSimons** [comment]
有需求自己fork，我不要你觉得，我要我觉得。

**Comment by Ozzy-hzy** [comment]
> 有需求自己fork，然后修改自己用。 我不要你觉得，我要我觉得。

提个建议啦，我只是觉得用户如果关闭这个插件后原本的ipv6网站访问不了了，一时间可能找不到问题所在。
