### ISSUE TITLE
DNS设置助手没有起效

### ISSUE THREAD

**Issue by iwrt** [QiuSimons/openwrt-mos#62]
如题，点击了dns设置后。然后去看passwall里面的配置。没有起作用。不知道是不是个例。

**Comment by geryson911** [comment]
我和你一样 也无法开启  显示运行后过会就自己关闭了  默认配置

**Comment by QiuSimons** [comment]
log呢？mosdns的luci版本呢？passwall的luci版本呢？
就一定要算命么？

**Comment by iwrt** [comment]
luci-app-passwall | 4.46-2最新版，mosdns也是最新luci-app-mosdns | 1.2-1   问题是点击 “DNS 设置助手” 后面的应用。然后跑到passwall那边去看，dns的过滤模式  并没有发生改变。系统日志：
Mon Jan 17 14:31:00 2022 cron.err crond[20253]: USER root pid 4391 cmd /usr/bin/set_kernel_timezone >/dev/null 2>&1
Mon Jan 17 14:33:14 2022 cron.err crond[6360]: crond (busybox 1.34.1) started, log level 5
Mon Jan 17 14:33:16 2022 cron.err crond[6434]: crond (busybox 1.34.1) started, log level 5
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.045+0800	info	v3/main.go:157	current working directory: /etc/mosdns/
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.046+0800	info	v3/main.go:223	mosdns ver: v3.0.0
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.046+0800	info	v3/main.go:224	arch: amd64, os: linux, go: go1.17.6
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.046+0800	info	coremain/run.go:67	loading config	{"file": "./def_config.yaml"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.046+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.loglv"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.048+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.loglv", "stdout": "error"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.048+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.logfile"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.049+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.logfile", "stdout": "/dev/null"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.049+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns0.sh"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.064+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns0.sh", "stdout": "221.12.1.227"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.064+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns1.sh"}
Mon Jan 17 14:33:17 2022 daemon.err mosdns[6662]: 2022-01-17T14:33:17.076+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns1.sh", "stdout": "221.12.33.227"}

**Comment by QiuSimons** [comment]
据我所知，passwall的最新版本是4.47.....
https://github.com/xiaorouji/openwrt-passwall/commits/main
check before you ask, PLEASE!

**Comment by 1wrt** [comment]
无论passwall是4.47还是4.46. mosdns的DNS “设置助手” 后面的”应用“后，passwall均没有设置。18.06和19.07和21.02以及master分支，我都试过。ssr则没有此问题。
