### ISSUE TITLE
重启后忽略解析文件未勾选

### ISSUE THREAD

**Issue by Ozzy-hzy** [QiuSimons/openwrt-mos#63]
开启mosdns后DHCP/DNS----HOSTS和解析文件----忽略解析文件会打勾，但重启后这个勾被取消了，对mosdns解析有影响吗

**Comment by Ozzy-hzy** [comment]
> 开启mosdns后DHCP/DNS----HOSTS和解析文件----忽略解析文件会打勾，但重启后这个勾被取消了，对mosdns解析有影响吗

看了用自定义配置好像不会变这个选项，想问下这个选项对mosdns做dnsmasq上游有影响吗

**Comment by Pacio** [comment]
OP的问题，很多DNS插件都需要设置忽略，但是重启以后又会被自动取消
