### ISSUE TITLE
希望能增加全部直连的预设

### ISSUE THREAD

**Issue by EsuRt** [QiuSimons/openwrt-mos#64]
平时用自定义配置比较多，但需要手动修改dns转发和忽略解析文件，每次临时关闭passwall等服务后需要重置之前的设置，能否提供一个全部直连的预设，这样即使在已经设置dns转发和忽略解析文件的前提下，也能正常访问国外网站（passwall关闭后，不重置dns转发，在dns分流的配置下，会出现国外网站无法解析的情况）。

**Comment by QiuSimons** [comment]
自定义模式的意义就是要让有能力的用户自行解决问题的....

**Comment by EsuRt** [comment]
其实是平时要用多种自定义配置，但目前只有一个配置，如果需要切换，就要修改自定义配置，不知能否添加多个自定义配置，从而到达快速切换的目的。

**Comment by QiuSimons** [comment]
多个自定义配置这个需求或许太小众了，我这边可能不会跟进这种功能需求，或者您可以尝试自行添加此功能，完工后欢迎pr
