### ISSUE TITLE
疑似跟xray有启动顺序问题？

### ISSUE THREAD

**Issue by Jan20th9e** [QiuSimons/openwrt-mos#65]
与 https://github.com/QiuSimons/openwrt-mos/issues/48 情况类似。
搭配ssrp时使用vmess节点“使用xray”时启用mosdns和ssrp后，即使无修改重新保存mosdns后或者wan重新拨号后，ssrp国外就不通了，只能重新保存并应用ssrp后恢复正常。如果使用的是ss节点一切正常，上述情况不会发生。

配置文件
log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - main_sequence
      server:
        - protocol:        udp
          addr:            ':5335'
        - protocol:        tcp
          addr:            ':5335'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _end
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _end
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback:   150
          always_standby:  true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            'https://223.5.5.5/dns-query'
  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://8.8.4.4'
          idle_timeout:    10
        - addr:            'tls://1.0.0.1'
          idle_timeout:    10
        - addr:            'tls://9.9.9.9'
          idle_timeout:    10

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

**Comment by Jan20th9e** [comment]
另外发现一个状况不知有人遇到过没，路由器开启ipv6后，部分网站似乎会被污染，比如v2ex.com间接性打不开，按道理mosdns作为dnsmasq上游且配置了ipv4优先应该不是ipv6抢答，但是实际情况关闭ipv6后就没问题了。看起来怀疑是ipv6哪侧漏了。

**Comment by jliveusa** [comment]
后面解决了吗？
