### ISSUE TITLE
killall导致启用后显示未运行

### ISSUE THREAD

**Issue by Ozzy-hzy** [QiuSimons/openwrt-mos#66]
在终端里输入
`/etc/init.d/modns reload`
显示Terminated，网上搜了下可能是killall modns将本身这个进程杀掉了，于是改成
`ps -w | grep -v "grep" | grep "/usr/bin/mosdns" | awk '{print $1}' | xargs kill -9`
重新点保存并应用，已经显示运行中。

**Comment by zhengjun131461** [comment]
文件应该怎么改呀？

**Comment by Ozzy-hzy** [comment]
> 文件应该怎么改呀？

/etc/init.d/mosdns文件里，最后的stop函数里，`killall mosdns`改成`ps -w | grep -v "grep" | grep "/usr/bin/mosdns" | awk '{print $1}' | xargs kill -9`
