### ISSUE TITLE
能否添加一个小功能？

### ISSUE THREAD

**Issue by THINK37** [QiuSimons/openwrt-mos#70]
首先感谢大佬的解决了京东无法访问的问题,现在就剩一个小米电饭煲的问题，刚才更新完，规则后还是无法连接设备,只能局域网使用，能否添加一个小功能，我可以选择设备IP直接连接网络，不经过MOSDNS的定向或者是过滤，就像SSRP那个不走代理的局域网LAN IP
![微信图片_20220208143300](https://user-images.githubusercontent.com/98004940/152931402-4d801017-5f12-4b45-9405-1dd3b6b1f683.jpg)
![微信图片_20220208143312](https://user-images.githubusercontent.com/98004940/152931413-249cc4f2-3fa9-41cd-b482-c9981e874725.jpg)
![微信图片_20220208143341](https://user-images.githubusercontent.com/98004940/152931416-0c466d3a-a86c-4e09-99bf-66f9da2ab05e.jpg)
![微信图片_20220208143345](https://user-images.githubusercontent.com/98004940/152931421-0fe2c582-96bf-4276-8516-099b7af9699e.jpg)

**Comment by QiuSimons** [comment]
不知道它访问的具体是什么域名，不过增加了白名单功能，自行尝试吧
