### ISSUE TITLE
更新之后数据库之后MosDNS 未运行

### ISSUE THREAD

**Issue by THINK37** [QiuSimons/openwrt-mos#76]
更新之后数据库之后MosDNS 未运行
![1644554516(1)](https://user-images.githubusercontent.com/98004940/153538631-f89908b4-164d-4424-a8fc-2f4c1d85a99f.jpg)

**Comment by QiuSimons** [comment]
/etc/mosdns/
目录下新建个whitelist.txt

**Comment by THINK37** [comment]
> /etc/mosdns/ 目录下新建个whitelist.txt

好的，解决了

**Comment by THINK37** [comment]
> > /etc/mosdns/ 目录下新建个whitelist.txt
> 
> 好的，解决了
又不行了
![S9LDN5MGS73P SR1 1YK(GR](https://user-images.githubusercontent.com/98004940/153737733-9f491fb3-0cdc-4559-985f-698748dee5d2.png)
![6_H`E23I655W(4@5WQREMMO](https://user-images.githubusercontent.com/98004940/153737735-1eaba209-d776-4080-ac62-a9efa910be0e.png)

**Comment by QiuSimons** [comment]
重新编译更新插件

**Comment by THINK37** [comment]
> 重新编译更新插件

要怎么操作呢？还是等您这边操作？

**Comment by QiuSimons** [comment]
> 然应该无论如何都无法

直接编译新插件，或者用新编译好的固件

**Comment by THINK37** [comment]
> > 本来应该都不能
> 
> 直接编译新插件，或者用新编译好的固件


> > 然应该无论如何都无法
> 
> 直接编译新插件，或者用新编译好的固件

好的，解决了，米家那个问题也解决了
