### ISSUE TITLE
开启启用数据库自动更新之后，无法自动更新配置文件，需要手动更新

### ISSUE THREAD

**Issue by THINK37** [QiuSimons/openwrt-mos#79]
开启启用数据库自动更新之后，好像没办法启动,数据没有更新，MosDNS数据还是上次手动更新的时间，手动更新没有问题

**Comment by dsyo2008** [comment]
同样问题，需要手动更新正常

**Comment by THINK37** [comment]
还是不行
![微信图片_20220218130853](https://user-images.githubusercontent.com/98004940/154621419-5cf41519-33fa-4b7d-90a1-b3e43dec9401.png)

![微信图片_20220218130847](https://user-images.githubusercontent.com/98004940/154621407-6e1c7bd7-d980-4897-a3d8-7c2ba7c1d8f7.png)
