### ISSUE TITLE
还是#79一样的问题，更新配置还是无法更新

### ISSUE THREAD

**Issue by THINK37** [QiuSimons/openwrt-mos#80]
#79
![微信图片_20220218130847](https://user-images.githubusercontent.com/98004940/154621574-42670428-eef3-4d20-84bf-6e3a592de14c.png)
![微信图片_20220218130853](https://user-images.githubusercontent.com/98004940/154621579-51743fac-564b-4bb5-9b4a-9cfb8c87e7de.png)

**Comment by QiuSimons** [comment]
？？？？？
你重新编译了？

**Comment by QiuSimons** [comment]
和更新配置有什么关系？？？

**Comment by QiuSimons** [comment]
你用新源码还是不行？

**Comment by THINK37** [comment]
> 你用新源还是不行？

不好意思，我重新编译一下。
