### ISSUE TITLE
OP安装错误提示Unknown package

### ISSUE THREAD

**Issue by smdx** [QiuSimons/openwrt-mos#81]
各位好，请问在OP文件传输安装提示
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest. Unknown package 'luci-app-mosdns'.
要怎么处理？谢谢
![2022-02-20_105849](https://user-images.githubusercontent.com/9279217/154826710-411efacd-27ec-46cc-91d0-65d72698ce62.jpg)

PVE LXC运行OP 版本：ImmortalWrt 18.06-5.4-SNAPSHOT r11658-c1f1a6dd04
![2022-02-20_105901](https://user-images.githubusercontent.com/9279217/154826766-fb7d9f97-4753-4f91-be97-e8e394c83daf.jpg)

**Comment by QiuSimons** [comment]
依赖问题自行解决

**Comment by smdx** [comment]
好的，谢谢。

**Comment by daiaji** [comment]
手动编译openwrt可能还容易点。
