### ISSUE TITLE
mosdns无法启用

### ISSUE THREAD

**Issue by THINK37** [QiuSimons/openwrt-mos#88]
更新R2S-GC404-Docker-2022-03-02-21.02.2-sfs.zip这个固件后，点击启用后显示MosDNS 未运行，点击DNS 设置助手后，也无法启动
![FireShot Capture 001 - OpenWrt - 基本设置 - LuCI - 192 168 2 1](https://user-images.githubusercontent.com/98004940/156594037-646413e7-b6c5-4294-a105-e369424b2658.png)

**Comment by QiuSimons** [comment]
更新以后解决
