### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by starxu1971** [QiuSimons/openwrt-mos#91]
在Lean大的系统没法运行。自定义配置报端口占用，默认配置报脚本错误。

**Comment by starxu1971** [comment]
sdns[32320]: 2022-03-12T14:38:11.809+0800	info	coremain/run.go:67	loading config	{"file": "./cus_config.yaml"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.815+0800	info	coremain/run.go:133	loading plugin	{"tag": "main_server"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.816+0800	info	coremain/run.go:133	loading plugin	{"tag": "mem_cache"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.816+0800	info	coremain/run.go:133	loading plugin	{"tag": "ecs-cn"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	coremain/run.go:133	loading plugin	{"tag": "modify_ttl"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	coremain/run.go:133	loading plugin	{"tag": "main_sequence"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	main_server	server/server.go:205	server started	{"proto": "tcp", "addr": "[::1]:5335"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	coremain/run.go:133	loading plugin	{"tag": "local"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	main_server	server/server.go:205	server started	{"proto": "udp", "addr": "[::1]:5335"}
Sat Mar 12 14:38:11 2022 daemon.info mosdns[32320]: 2022-03-12T14:38:11.817+0800	info	coremain/run.go:133	loading plugin	{"tag": "remote"}
Sat Mar 12 14:38:11 2022 daemon.err mosdns[32320]: 2022-03-12T14:38:11.817+0800	fatal	main_server	server/server.go:129	server exited unexpectedly	{"error": "listen tcp 127.0.0.1:5335: bind: address already in use"}
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.836+0800	info	v3/main.go:157	current working directory: /etc/mosdns/
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.836+0800	info	v3/main.go:223	mosdns ver: v3.4.0
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.836+0800	info	v3/main.go:224	arch: amd64, os: linux, go: go1.17.8
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.837+0800	info	coremain/run.go:67	loading config	{"file": "./cus_config.yaml"}
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.842+0800	info	coremain/run.go:133	loading plugin	{"tag": "main_server"}
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.844+0800	info	main_server	server/server.go:205	server started	{"proto": "udp", "addr": "[::1]:5335"}
Sat Mar 12 14:38:16 2022 daemon.info mosdns[32355]: 2022-03-12T14:38:16.845+0800	info	main_server	server/server.go:205	server started	{"proto": "tcp", "addr": "[::1]:5335"}
Sat Mar 12 14:38:16 2022 daemon.err mosdns[32355]: 2022-03-12T14:38:16.845+0800	fatal	main_server	server/server.go:129	server exited unexpectedly	{"error": "listen tcp 127.0.0.1:5335: bind: address already in use"}

**Comment by starxu1971** [comment]
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.288+0800	info	v3/main.go:157	current working directory: /etc/mosdns/
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.294+0800	info	v3/main.go:223	mosdns ver: v3.4.0
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.295+0800	info	v3/main.go:224	arch: amd64, os: linux, go: go1.17.8
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.295+0800	info	coremain/run.go:67	loading config	{"file": "./def_config.yaml"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.295+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.loglv"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.300+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.loglv", "stdout": "error"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.300+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "uci -q get mosdns.mosdns.logfile"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.308+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "uci -q get mosdns.mosdns.logfile", "stdout": "/dev/null"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.308+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 0"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.322+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 0", "stdout": "119.29.29.29"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.322+0800	info	coremain/cmd.go:15	executing config cmd	{"cmd": "./dns.sh 1"}
Sat Mar 12 14:28:36 2022 daemon.info mosdns[17501]: 2022-03-12T14:28:36.336+0800	info	coremain/cmd.go:21	successfully executed cmd	{"cmd": "./dns.sh 1", "stdout": "101.226.4.6"}

**Comment by daiaji** [comment]
更新版本。

**Comment by daiaji** [comment]
openwrt-mos/mosdns/Makefile
`PKG_VERSION:=b8dc845`
mosdns那边随便找个commit，换掉PKG_VERSION的值。
再编译看看？

**Comment by IrineSistiana** [comment]
```
Sat Mar 12 14:38:16 2022 daemon.err mosdns[32355]: 2022-03-12T14:38:16.845+0800 fatal main_server server/server.go:129 server exited unexpectedly {"error": "listen tcp 127.0.0.1:5335: bind: address already in use"}
```

明显是端口撞车了。跟内核什么的没关系。

`netstat -nplt` 看看跟谁撞了。

**Comment by starxu1971** [comment]
早看过了就没撞车的但是只要运行就报撞车

**Comment by starxu1971** [comment]
回退老版本马上一切正常

**Comment by IrineSistiana** [comment]
> 回老版本马上一切正常

很难确定是mos内核的问题还是luci-mosdns的问题。因为回老版本这两个都回滚了

既然你现在是老版本luci-mosdns能用，那就控制变量法。手动把新的mos内核复制替换到老版本luci-mosdns里。看看有什么现象。

**Comment by starxu1971** [comment]
好的我试试看替换

**Comment by starxu1971** [comment]
新版本内核也能运行

**Comment by IrineSistiana** [comment]
> 换掉PKG_VERSION的值 重新编译的就能运行

luci-mosdns 的版本？
mosdns的版本？

**Comment by IrineSistiana** [comment]
> 新版本内核也能运行

看来是 luci-mosdns 的问题了。

**Comment by starxu1971** [comment]
目前运行正常的版本luci-app-mosdns 1.2-1，mosdns 3.4.0-1

**Comment by starxu1971** [comment]
这是目前正常使用自定义配置
log:
  level: debug
  file: ""

plugin:
  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - mem_cache # 缓存
        - main_sequence # 运行主执行序列
        - modify_ttl # 修改 ttl
      server:
        - protocol: udp
          addr: "127.0.0.1:5335"
        - protocol: tcp
          addr: "127.0.0.1:5335"
        - protocol: udp
          addr: "[::1]:5335"
        - protocol: tcp
          addr: "[::1]:5335"
  ################# 可执行插件 ################

  # 缓存
  - tag: "mem_cache"
    type: "cache"
    args:
      size: 1024 # 条目数量
      lazy_cache_ttl: 86400 # lazy cache 生存时间
      lazy_cache_reply_ttl: 30 # 返回过期应答的 TTL

  - tag: "ecs-cn"
    type: "ecs"
    args:
      auto: false #仅适用于公网的服务器。本地运行不要启用这个功能。
      ipv4: "202.120.2.101" # 预设 IPv4
      ipv6: "2001:da8:8000:1:202:120:2:101" # 预设 IPv6
      force_overwrite: true # 强制覆盖
      mask4: 24 # 用于 ipv4 地址的掩码 默认: 24。
      mask6: 48 # 用于 ipv6 地址的掩码 默认: 48。

  # 修改应答 ttl
  - tag: "modify_ttl"
    type: "ttl"
    args:
      minimal_ttl: 300
      maximum_ttl: 3600

  ################ 序列 #################

  # main_sequence
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_ad # ad
          exec:
            - _block_with_nxdomain # 空应答
            - _end

        - if:
            - query_cn # cn域名
            - "!_query_is_common" # 不常见的请求
          exec:
            - ecs-cn
            - _pad_query
            - local # 用本地服务器
            - if:
                - "response_cnip" # 结果是 cnip
              exec:
                - _end # 结束

        - if:
            - query_notcn # 已知的 非cn域名
          exec:
            - _prefer_ipv4 # 优先 IPv4
            - _pad_query
            - remote # 无污染
            - if:
                - "!response_cnip" # 结果是 非cnip
              exec:
                - _end # 结束

        - primary: #其他所有情况
            - _prefer_ipv4
            - _pad_query
            - remote
          secondary:
            - _prefer_ipv4
            - _pad_query
            - local
          fast_fallback: 400 # 这里建议设置成 local 服务器正常延时的 2~5 倍 单位: 毫秒
          always_standby: true

  # local 序列
  - tag: local
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "ali" # 执行序列 #1。
                - - "dnspod" # 执行序列 #2。
          secondary:
            - localdns # 备用本地
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  # remote 序列
  - tag: remote
    type: sequence
    args:
      exec:
        - primary:
            - parallel: # 并行
                - - "google" # 执行序列 #1。
                - - "cloudflare" # 执行序列 #2。
          secondary:
            - adguard # 备用 adguard
          fast_fallback: 600 # 这里建议设置成 primary 服务器正常延时的 2~5 倍 单位: 毫秒。
          always_standby: true

  ################ DNS #################
  # 阿里 dns
  - tag: ali
    type: forward
    args:
      upstream:
        - addr: "https://dns.alidns.com/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2400:3200:baba::1"
            - "223.5.5.5"
            - "2400:3200::1"
            - "223.6.6.6"
          trusted: true # 是否是可信服务器
        - addr: "tls://dns.alidns.com" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2400:3200:baba::1"
            - "223.5.5.5"
            - "2400:3200::1"
            - "223.6.6.6"
          trusted: true # 是否是可信服务器

      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      fastest_ip: false # 优选最快 ip 对返回 ip 测速,可能会非常慢
      timeout: 5 # 请求超时时间秒

  # dnspod
  - tag: dnspod
    type: forward
    args:
      upstream:
        - addr: "https://doh.pub/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2402:4e00::"
            - "119.29.29.29"
          trusted: true # 是否是可信服务器
        - addr: "tls://dot.pub" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2402:4e00::"
            - "119.29.29.29"
          trusted: true # 是否是可信服务器

      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      fastest_ip: false # 优选最快 ip 对返回 ip 测速,可能会非常慢
      timeout: 5 # 请求超时时间秒

  # 本地 dns 备用
  - tag: localdns
    type: forward
    args:
      upstream:
        - addr: "192.168.1.1:53"

  # google dns
  - tag: google
    type: forward
    args:
      upstream:
        - addr: "https://dns.google/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2001:4860:4860::8844"
            - "8.8.4.4"
            - "2001:4860:4860::8888"
            - "8.8.8.8"
          trusted: true # 是否是可信服务器
        - addr: "tls://dns.google" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2001:4860:4860::8844"
            - "8.8.4.4"
            - "2001:4860:4860::8888"
            - "8.8.8.8"
          trusted: true # 是否是可信服务器
      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      fastest_ip: false # 优选最快 ip 对返回 ip 测速,可能会非常慢
      timeout: 5 # 请求超时时间秒

  # cloudflare
  - tag: cloudflare
    type: forward
    args:
      upstream:
        - addr: "https://cloudflare-dns.com/dns-query" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2606:4700:4700::1001"
            - "1.0.0.1"
            - "2606:4700:4700::1111"
            - "1.1.1.1"
          trusted: true # 是否是可信服务器
        - addr: "tls://cloudflare-dns.com" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2606:4700:4700::1001"
            - "1.0.0.1"
            - "2606:4700:4700::1111"
            - "1.1.1.1"
          trusted: true # 是否是可信服务器

      bootstrap:
        - "tls://1.1.1.1"
        - "https://223.5.5.5/dns-query"
      fastest_ip: false # 优选最快 ip 对返回 ip 测速,可能会非常慢
      timeout: 5 # 请求超时时间秒

  # doq 备用
  - tag: adguard
    type: forward
    args:
      upstream:
        - addr: "quic://dns-unfiltered.adguard" # 服务器地址
          ip_addr: # 手动指定服务器的 IP 地址 可以配置多个
            - "2a10:50c0::1:ff"
            - "94.140.14.140"
            - "2a10:50c0::2:ff"
            - "94.140.14.141"
          trusted: true # 是否是可信服务器

  ################ 匹配器 #################

  # 查询 - cn 域名
  - tag: query_cn
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:cn"

  # 查询 - gfw
  - tag: query_gfw
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:gfw"

  # 查询 - 非 cn 域名
  - tag: query_notcn
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:geolocation-!cn"

  # 查询 - ad
  - tag: query_ad
    type: query_matcher
    args:
      domain:
        - "ext:./geosite.dat:category-ads-all"

  # 返回 - cn IP
  - tag: response_cnip
    type: response_matcher
    args:
      ip:
        - "ext:./geoip.dat:cn"

**Comment by daiaji** [comment]
`pgrep -f /usr/bin/mosdns`
openwrt执行一下看看？

**Comment by starxu1971** [comment]
输出 18368

**Comment by daiaji** [comment]
/etc/init.d/mosdns stop 能杀掉进程吗？
杀掉之后再pgrep -f /usr/bin/mosdns

**Comment by starxu1971** [comment]
现在使用的版本能杀掉进程，输出23982

**Comment by daiaji** [comment]
那你明天手动启动试试吧。
`/usr/bin/mosdns -dir /etc/mosdns/ -c ./cus_config.yaml`

**Comment by starxu1971** [comment]
进程杀不死，杀掉过几秒又起来了

**Comment by starxu1971** [comment]
暂时不管了，现在这个混合体正常运行

**Comment by afeiy** [comment]
今天拉库编译的x86运行正常，主库是lean,额外加了kenzok8的openwrt-packages。[
![2022-03-15 164044](https://user-images.githubusercontent.com/59036420/158339889-17e59861-acf6-4753-87d4-4dabfed9c74c.png)
![2022-03-15 164007](https://user-images.githubusercontent.com/59036420/158339929-2ffbee05-3dbd-4786-a9e3-4a785fff157b.png)

**Comment by starxu1971** [comment]
手动更新了下核心，也能运行。现在拉库编译看看
