### ISSUE TITLE
自动更新配置那有点问题。

### ISSUE THREAD

**Issue by flyhong666** [QiuSimons/openwrt-mos#98]
不管是手动还是自动更新，或者点击启用MosDNS。都会将serverlist.txt 清空了，然后生成了serverlist.bak。能不能检查一下这是啥原因没更新文件呢。
![2022-04-20_144421](https://user-images.githubusercontent.com/76857714/164167017-cf95cba9-0d4d-46bb-a29e-dcf1ced1ed50.png)

**Comment by QiuSimons** [comment]
很简单啊，你没开启广告过滤啊

**Comment by flyhong666** [comment]
> 很简单啊，你没开启广告过滤啊，这是符合预期的行为

按你的说法，将广告过滤打开了，再点击更新还是同样的。现在bak都为零了。
![image](https://user-images.githubusercontent.com/76857714/164592721-d38b235c-efad-417a-9a53-28ebc5fdd279.png)
![image](https://user-images.githubusercontent.com/76857714/164592780-29f71c41-f1a0-454c-9f67-80e4cf8f38ec.png)

**Comment by flyhong666** [comment]
我明白了，这个要定时勾上自动才可以，手动更新不行。

**Comment by sbwml** [comment]
在官方原版固件测试了一下，你说的问题确实存在，他由wget 引起，修复：https://github.com/QiuSimons/openwrt-mos/pull/103

当系统不存在curl 的情况下，会使用默认的wget ，而openwrt 的wget 功能是很单一的，不具备 GNU Wget 所支持的一些参数
